### ISSUE TITLE
咦

### ISSUE THREAD

**Issue by DarrenMagician** [JSW5297/CoordinateTransform#1]
跟我之前star过的一个好像啊，说明都一模一样，确定是你自己写的？

**Comment by JSW5297** [comment]
这个我是借鉴了网上的资料的，当然不是完全由我写的，至于你说和那个的README一样？

**Comment by JSW5297** [comment]
本项目也是之前借鉴过网上的资料，并不是我个人完全独立完成的，我只是上次项目需要然后就整理了一下，封装给自己用了，若原作者（我也是不知是谁～）不希望我这样公开，请联系我，我会立马删除次项目

**Comment by JSW5297** [comment]
@DarrenMagician 我从你的star中看到了，你说的是这个吗？https://github.com/wandergis/coordtransform

我当时好像就是看的这个人的资料，但是我需要的是java版本的，他没有，所以我自己弄了一份，我当时也忘记star他了，我可以把我的java版本贡献给他的

**Comment by JSW5297** [comment]
@DarrenMagician   已通知原作者，看看原作者是否同意将此项目提交给他当java版本的
